# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Projekt2
                                 A QGIS plugin
 Projekt2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-03
        copyright            : (C) 2023 by M.Bielecki, M.Chwałek
        email                : m.bielecki1909@o2.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Projekt2 class from file Projekt2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Projekt2 import Projekt2
    return Projekt2(iface)
